# This is a basic workflow that is manually triggered

name: Manual Publish

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      username:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Username of account to publish under.'
        # Input has to be provided for the workflow to run
        required: true
      oauth:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Oauth token of account to publish under.'
        # Input has to be provided for the workflow to run
        required: true






# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    # Runs a single command using the runners shell
    - name: Do publish
      run: npm run post -- --username "${{ github.event.inputs.username }}" --oauth "${{ github.event.inputs.oauth }}" --real
      
      
      
      
      
      
      
      
